#:schema node_modules/wrangler/config-schema.json
# For more details on how to configure Wrangler, refer to:
# https://developers.cloudflare.com/workers/wrangler/configuration/
name = "personal-bookmarks"
compatibility_date = "2025-07-05"
main = "./build/server/index.js"

[vars]
MY_VAR = "my-variable"

# Note: Use secrets to store sensitive data.
# https://developers.cloudflare.com/workers/configuration/secrets/

# Static Assets
# https://developers.cloudflare.com/workers/static-assets/binding/

# Service Bindings (communicate between multiple Workers)
# https://developers.cloudflare.com/workers/wrangler/configuration/#service-bindings
# [[services]]
# binding = "MY_SERVICE"
# service = "my-service"

[[r2_buckets]]
binding = "DB" # 在代码中使用的别名
bucket_name = "personal-bookmarks-data-skci" # 你的 R2 存储桶名称
